// Pool de nombres temáticos griegos para identificar mesas.
// Filósofos, mitología y conceptos / palabras filosóficas.
export const GREEK_NAMES: readonly string[] = [
  // Filósofos
  "Sócrates",
  "Platón",
  "Aristóteles",
  "Pitágoras",
  "Heráclito",
  "Demócrito",
  "Epicuro",
  "Diógenes",
  "Tales",
  "Anaximandro",
  "Empédocles",
  "Parménides",
  "Zenón",
  "Plotino",
  "Crisipo",
  "Hipócrates",
  "Arquímedes",
  "Euclides",
  // Mitología — dioses olímpicos
  "Zeus",
  "Hera",
  "Atenea",
  "Apolo",
  "Ares",
  "Hermes",
  "Artemisa",
  "Afrodita",
  "Hefesto",
  "Hades",
  "Poseidón",
  "Dionisio",
  "Deméter",
  "Hestia",
  // Mitología — héroes y otros
  "Hércules",
  "Perseo",
  "Aquiles",
  "Odiseo",
  "Jasón",
  "Teseo",
  "Orfeo",
  "Prometeo",
  "Pandora",
  "Helena",
  "Casandra",
  "Ícaro",
  "Dédalo",
  // Conceptos / palabras
  "Ataraxia",
  "Eudaimonía",
  "Logos",
  "Cosmos",
  "Sophia",
  "Areté",
  "Hubris",
  "Kairós",
  "Stoa",
  "Pathos",
  "Ethos",
  "Aporía",
  "Telos",
  "Praxis",
  "Phrónesis",
  "Eros",
  "Ágape",
  "Ananké",
  "Tyche",
  "Moira",
  "Némesis",
  "Iris",
  "Euforia",
  "Mnemósine",
  "Hipnos",
  "Tánatos",
];

export function randomGreekName(): string {
  const idx = Math.floor(Math.random() * GREEK_NAMES.length);
  return GREEK_NAMES[idx] ?? GREEK_NAMES[0]!;
}
